###########################################################################
#
#   Copyright (C) 2026. All rights reserved.
#
#   SPDX-License-Identifier: Apache-2.0
#
###########################################################################

# C sources
MAINSRC = src/watchface_main.c \
          src/honeycomb_model.c \
          assets/wf_data.c \
          src/font_zh_16.c \
          src/font_zh_20.c \
          src/buttons.c \
          src/sensor_imu.c \
          src/watch_power.c \
          src/watch_haptics.c \
          src/watch_board.c

include $(APPDIR)/Application.mk
