#!/bin/bash
set -euo pipefail

export KCONFIG_CONFIG=/home/cmake_out/lckfb_huangshan_pi/.config
export EXTERNALDIR=dummy
export APPSDIR=/home/nuttx-apps
export DRIVERS_PLATFORM_DIR=dummy
export APPSBINDIR=/home/cmake_out/lckfb_huangshan_pi/nuttx-apps
export BINDIR=/home/cmake_out/lckfb_huangshan_pi

cd /home/nuttx

setconfig \
  EXAMPLES_ADC=n \
  EXAMPLES_ADC_SWTRIG=n \
  EXAMPLES_BUTTONS=n \
  EXAMPLES_BUTTONS_NAMES=n \
  EXAMPLES_BUTTONS_POLL=n \
  EXAMPLES_FB=n \
  EXAMPLES_GPIO=n \
  EXAMPLES_HELLO=n \
  EXAMPLES_LSM6DSL_READER=n \
  EXAMPLES_LVGLDEMO=n \
  EXAMPLES_PWM=n \
  EXAMPLES_TIMER=n \
  EXAMPLES_WATCHDOG=n \
  LV_BUILD_EXAMPLES=n \
  LV_USE_DEMO_WIDGETS=n \
  LV_USE_RLE=y \
  LV_BIN_DECODER_RAM_LOAD=y \
  LV_CACHE_DEF_SIZE=524288 \
  LV_USE_FREETYPE=n \
  LV_USE_LIBPNG=n \
  LV_USE_QRCODE=n \
  LV_USE_VECTOR_GRAPHIC=n \
  LV_USE_ANIMIMG=n \
  LV_USE_ARC=y \
  LV_USE_BAR=n \
  LV_USE_BUTTONMATRIX=n \
  LV_USE_CALENDAR=n \
  LV_USE_CALENDAR_HEADER_ARROW=n \
  LV_USE_CALENDAR_HEADER_DROPDOWN=n \
  LV_USE_CANVAS=y \
  LV_USE_CHART=n \
  LV_USE_CHECKBOX=n \
  LV_USE_DROPDOWN=n \
  LV_USE_IMAGEBUTTON=n \
  LV_USE_KEYBOARD=n \
  LV_USE_LED=n \
  LV_USE_LIST=n \
  LV_USE_MENU=n \
  LV_USE_MSGBOX=n \
  LV_USE_ROLLER=n \
  LV_USE_SCALE=n \
  LV_USE_SLIDER=n \
  LV_USE_SPAN=n \
  LV_USE_SPINBOX=n \
  LV_USE_SPINNER=n \
  LV_USE_SWITCH=n \
  LV_USE_TABLE=n \
  LV_USE_TABVIEW=n \
  LV_USE_TEXTAREA=n \
  LV_USE_TILEVIEW=n \
  LV_USE_WIN=n \
  LV_FONT_MONTSERRAT_10=y \
  LV_FONT_MONTSERRAT_16=y \
  LV_FONT_MONTSERRAT_24=y \
  LV_FONT_MONTSERRAT_36=y \
  LV_FONT_MONTSERRAT_48=y \
  LIBUV=n \
  NETUTILS_CJSON=n \
  --kconfig /home/nuttx/Kconfig

echo "Applied optimized config:"
grep -E '^CONFIG_(EXAMPLES_ADC|EXAMPLES_LVGLDEMO|LV_USE_DEMO_WIDGETS|LIBUV|LV_USE_FREETYPE|LV_USE_LIBPNG|NETUTILS_CJSON)=|^# CONFIG_(EXAMPLES_ADC|EXAMPLES_LVGLDEMO|LV_USE_DEMO_WIDGETS|LIBUV|LV_USE_FREETYPE|LV_USE_LIBPNG|NETUTILS_CJSON) is not set' "$KCONFIG_CONFIG"
