#!/bin/bash
set -euo pipefail

DEFCONFIG=/home/vendor/sifli/boards/sf32lb52/lckfb_huangshan_pi/configs/nsh/defconfig

cp "$DEFCONFIG" "$DEFCONFIG.pre-optimize"

# Remove any existing choice lines first so the explicit "not set" lines
# below are the single source of truth after Kconfig regeneration.
symbols=(
  CONFIG_EXAMPLES_ADC
  CONFIG_EXAMPLES_ADC_SWTRIG
  CONFIG_EXAMPLES_BUTTONS
  CONFIG_EXAMPLES_BUTTONS_NAMES
  CONFIG_EXAMPLES_BUTTONS_POLL
  CONFIG_EXAMPLES_FB
  CONFIG_EXAMPLES_GPIO
  CONFIG_EXAMPLES_HELLO
  CONFIG_EXAMPLES_LSM6DSL_READER
  CONFIG_EXAMPLES_LVGLDEMO
  CONFIG_EXAMPLES_PWM
  CONFIG_EXAMPLES_TIMER
  CONFIG_EXAMPLES_WATCHDOG
  CONFIG_LV_BUILD_EXAMPLES
  CONFIG_LV_USE_DEMO_WIDGETS
  CONFIG_LV_USE_FREETYPE
  CONFIG_LV_USE_LIBPNG
  CONFIG_LV_USE_QRCODE
  CONFIG_LV_USE_VECTOR_GRAPHIC
  CONFIG_LV_USE_ANIMIMG
  CONFIG_LV_USE_ARC
  CONFIG_LV_USE_BAR
  CONFIG_LV_USE_BUTTONMATRIX
  CONFIG_LV_USE_CALENDAR
  CONFIG_LV_USE_CALENDAR_HEADER_ARROW
  CONFIG_LV_USE_CALENDAR_HEADER_DROPDOWN
  CONFIG_LV_USE_CANVAS
  CONFIG_LV_USE_CHART
  CONFIG_LV_USE_CHECKBOX
  CONFIG_LV_USE_DROPDOWN
  CONFIG_LV_USE_IMAGEBUTTON
  CONFIG_LV_USE_KEYBOARD
  CONFIG_LV_USE_LED
  CONFIG_LV_USE_LIST
  CONFIG_LV_USE_MENU
  CONFIG_LV_USE_MSGBOX
  CONFIG_LV_USE_ROLLER
  CONFIG_LV_USE_SCALE
  CONFIG_LV_USE_SLIDER
  CONFIG_LV_USE_SPAN
  CONFIG_LV_USE_SPINBOX
  CONFIG_LV_USE_SPINNER
  CONFIG_LV_USE_SWITCH
  CONFIG_LV_USE_TABLE
  CONFIG_LV_USE_TABVIEW
  CONFIG_LV_USE_TEXTAREA
  CONFIG_LV_USE_TILEVIEW
  CONFIG_LV_USE_WIN
  CONFIG_LV_FONT_MONTSERRAT_16
  CONFIG_LV_FONT_MONTSERRAT_24
  CONFIG_LIBUV
  CONFIG_LIBUV_EXTENSION
  CONFIG_LV_USE_NUTTX_LIBUV
  CONFIG_NETUTILS_CJSON
)

for sym in "${symbols[@]}"; do
  sed -i "/^${sym}=y$/d; /^# ${sym} is not set$/d" "$DEFCONFIG"
done

{
  echo ''
  echo '# --- Codex product-image trim: keep the watch UI lean ---'
  for sym in "${symbols[@]}"; do
    echo "# ${sym} is not set"
  done
} >> "$DEFCONFIG"

echo "Trimmed $DEFCONFIG"
grep -E '^CONFIG_(EXAMPLES_WATCHFACE|GRAPHICS_LVGL|LV_USE_IMAGE|LV_USE_LABEL|LV_USE_BUTTON|LV_USE_LINE|LV_USE_FLEX|SYSTEM_NSH)=y$' "$DEFCONFIG"
